<?xml version="1.0" encoding="utf-8"?>

<!DOCTYPE products 
[
  <!--ТОВАРЫ-->
  <!ELEMENT products (product)*>

  <!--ТОВАР-->
  <!ELEMENT product (name_of_product, price, in_stock, type, brand, shipment)>

  <!--АТРИБУТЫ ТОВАРА-->
  <!ATTLIST product product_id CDATA #REQUIRED>

  <!--ЭЛЕМЕНТЫ ТОВАРА-->

  <!ELEMENT name_of_product (#PCDATA)>
  <!ELEMENT price (#PCDATA)>
  <!ELEMENT in_stock (#PCDATA)>

  <!--ТИП ТОВАРА-->
  <!ELEMENT type (name_of_type)>
  <!ATTLIST type type_id CDATA #REQUIRED>
  <!ELEMENT name_of_type (#PCDATA)>

  <!--МАРКА-->
  <!ELEMENT brand (name_of_brand, country_of_origin)>
  <!ATTLIST brand brand_id CDATA #REQUIRED>
  <!ELEMENT name_of_brand (#PCDATA)>
  <!ELEMENT country_of_origin (#PCDATA)>

  <!--ПОСТАВКА-->
  <!ELEMENT shipment (date_of_shipment, provider)>
  <!ATTLIST shipment shipment_id CDATA #REQUIRED>
  <!ELEMENT date_of_shipment (#PCDATA)>

  <!--ПОСТАВЩИК-->
  <!ELEMENT provider (name_of_provider, employee, phone_number, address)>
  <!ATTLIST provider provider_id CDATA #REQUIRED>
  <!ELEMENT name_of_provider (#PCDATA)>
  <!ELEMENT employee (#PCDATA)>
  <!ELEMENT phone_number (#PCDATA)>
  <!ELEMENT address (#PCDATA)>
]>


<products>

    <product product_id="product_1">

      <name_of_product>Смартфон Apple iPhone SE 2020</name_of_product>

      <price>43 199,00 РУБ</price>

      <in_stock>12</in_stock>
      
      <type type_id="type_1">
        <name_of_type>Смартфон</name_of_type>
      </type>

      <brand brand_id="brand_1">
        <name_of_brand>Apple</name_of_brand>
        <country_of_origin>Китай</country_of_origin>
      </brand>
      
      <shipment shipment_id="shipment_3">
        <date_of_shipment>8 июля 2021 г.</date_of_shipment>
        <provider provider_id="provider_3">
          <name_of_provider>MainApple</name_of_provider>
          <employee>Летов Савелий Иннокентиевич</employee>
          <phone_number>8-945-475-12-56</phone_number>
          <address>Москва, Романов пер, д 4 стр 2, пом II комн 54</address>
        </provider>
      </shipment>

    </product>
  
    <product product_id="product_2">
      <name_of_product>Смартфон Xiaomi Redmi 9A</name_of_product>
      <price>8 999,00 РУБ</price>
      <in_stock>15</in_stock>
      <type type_id="type_1">
        <name_of_type>Смартфон</name_of_type>
      </type>
      <brand brand_id="brand_2">
        <name_of_brand>Xiaomi</name_of_brand>
        <country_of_origin>Китай</country_of_origin>
      </brand>
      <shipment shipment_id="shipment_1">
        <date_of_shipment>10 июня 2021 г.</date_of_shipment>
        <provider provider_id="provider_1">
          <name_of_provider>Марвел-Дистрибуция</name_of_provider>
          <employee>Седыха Евгения Фомевна</employee>
          <phone_number>8-947-522-36-26</phone_number>
          <address>196084 Санкт-Петербург, ул. Киевская, д. 5, корп. 3</address>
        </provider>
      </shipment>
    </product>
  
    <product product_id="product_3">
      <name_of_product>Смарт-часы Apple Watch Series 3</name_of_product>
      <price>17 099,00 РУБ</price>
      <in_stock>4</in_stock>
      <type type_id="type_2">
        <name_of_type>Смарт-часы</name_of_type>
      </type>
      <brand brand_id="brand_1">
        <name_of_brand>Apple</name_of_brand>
        <country_of_origin>Китай</country_of_origin>
      </brand>
      <shipment shipment_id="shipment_3">
        <date_of_shipment>8 июля 2021 г.</date_of_shipment>
        <provider provider_id="provider_3">
          <name_of_provider>MainApple</name_of_provider>
          <employee>Летов Савелий Иннокентиевич</employee>
          <phone_number>8-945-475-12-56</phone_number>
          <address>Москва, Романов пер, д 4 стр 2, пом II комн 54</address>
        </provider>
      </shipment>
    </product>
  
  </products>
  
